### ISSUE TITLE
Synchronising ZoneJumps and Geoemtry in Dungeons and Cities

### ISSUE THREAD

**Issue by firesgc** [dol-leodagan/DaocClientLib#1]
Hey! 

First of all, thank you so much for this project! It's fantastic!
I know this project hasn't been worked on for a long time, but I hope you can help me.

I'm trying to "synchronize" the ZoneJumps of a dungeon (eg: Region 489 - Demons Breach) and the Dungeon Geometry, but I can't find anywhere how to calculate the offset of the Geometry to the Zone :(.  Do you know how/where this can be calculated?

Thank you very much!

ps: I think whenever regions consist of models (like dungeons and cities), there has to be an offset somewhere to synchronise model and ZoneJumps, StartPositions etc.

**Comment by dol-leodagan** [comment]
Hello,

This is really old, I remember that in the Game Engine there is a default 8192 units offset for City / Dungeon / Sky City Zone Type.

I can't say if this is actually the offset used inside the client data files though.

I remember being stuck while trying to understand Dungeon water areas coordinates, so there is still some geometry not handled in this project...

**Comment by firesgc** [comment]
You are right. It seems that they use hard-coded constants.
For cities it is vec3((15616, 15616, 8000) and for dungeons vec3(15616, 15616, 4000).
I havn't tested all dungeons but at least a dozen :)

Really strange that it's not data-driven like the rest :/

Thanks for your help!
